### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by popest** [fsmMLK/inkscapeCircuitSymbols#22]
When I click on apply, this error message is reported. Does anyone know what is wrong? Thank you

Traceback (most recent call last):
  File "circuitSymbols.py", line 6, in <module>
    from drawAmpOp import ampOp
  File "C:\Users\Stani\AppData\Roaming\inkscape\extensions\circuitSymbols\drawAmpOp.py", line 3, in <module>
    import inkscapeMadeEasy.inkscapeMadeEasy_Base as inkBase
  File "C:\Users\Stani\AppData\Roaming\inkscape\extensions\inkscapeMadeEasy\inkscapeMadeEasy_Base.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by fsmMLK** [comment]
did you modify inkscapeMadeEasy_Base.py?

Check line 7 of this file. It should start with a #. I have no idea why you are having this error.
